import test from 'node:test';
import assert from 'node:assert/strict';
import { initialState,applyCommand,CONTRACTS,evaluationWindow,evaluationRows,scoped,filterOccurrences,patterns,alertsFor,csvCell,evaluationStats } from '../src/transport/domain.js';
const manager={role:'seafin',name:'Teste'};const school={role:'school',schoolId:'school-001',name:'Escola de teste'};
const draft={schoolId:'school-001',cie:'0001',contractId:CONTRACTS[0].id,date:'2026-08-28',time:'08:30',vehicle:'V1',driver:'M1',place:'Portão',type:'Atraso',description:'Teste automatizado',severity:'Alto',evidences:[{id:'test'}]};
const call=(state,type,data,actor=manager,now='2026-08-28T12:00:00Z',day='2026-08-28')=>applyCommand(state,{type,data},actor,now,day);
test('Transporte começa vazio, com apenas os quatro contratos fornecidos',()=>{assert.equal(CONTRACTS.length,4);assert.equal(initialState().occurrences.length,0);assert.equal(initialState().assignments.length,0);});
test('Protocolos sequenciais, UUIDs distintos e gravidade original preservada',()=>{const a=call(initialState(),'createOccurrence',draft,school);const b=call(a.state,'createOccurrence',draft,school);assert.equal(a.result.protocol,'TR-2026-0001');assert.equal(b.result.protocol,'TR-2026-0002');assert.notEqual(a.result.id,b.result.id);assert.equal(b.result.severity,'Alto');});
test('Escopo escolar bloqueia escrita e leitura de outra unidade',()=>{assert.throws(()=>call(initialState(),'createOccurrence',{...draft,schoolId:'school-002'},school));assert.equal(scoped([{schoolId:'school-002'}],school).length,0);assert.equal(scoped([{schoolId:'school-001'}],null).length,0);});
test('Outros, evidências e data exigem preenchimento válido',()=>{for(const change of [{type:'Outros'},{evidences:[]},{date:'2026-02-30'},{date:'2027-01-01'},{time:'30:00'}])assert.throws(()=>call(initialState(),'createOccurrence',{...draft,...change},school));});
test('Workflow mantém histórico, bloqueia escola e detecta versão obsoleta',()=>{const a=call(initialState(),'createOccurrence',draft,school);const update={id:a.result.id,expectedVersion:a.result.updatedAt,status:'Em atendimento',responsible:'SEAFIN',note:'Contato realizado',reviewedSeverity:'Médio'};assert.throws(()=>call(a.state,'treatOccurrence',update,school));const b=call(a.state,'treatOccurrence',update,manager,'2026-08-29T12:00:00Z');assert.equal(b.result.history.length,2);assert.equal(b.result.history[1].from,'Aberta');assert.equal(b.result.severity,'Alto');assert.equal(b.result.reviewedSeverity,'Médio');assert.throws(()=>call(b.state,'treatOccurrence',update));});
test('Abertura cinco dias antes do fim: meses longos, curtos e bissexto',()=>{assert.deepEqual(evaluationWindow('2026-08'),{opens:'2026-08-26',due:'2026-08-31'});assert.equal(evaluationWindow('2026-02').opens,'2026-02-23');assert.equal(evaluationWindow('2028-02').opens,'2028-02-24');assert.throws(()=>evaluationWindow('2026-13'));});
function configured(){let s=call(initialState(),'assignment',{schoolId:'school-001',cie:'0001',contractId:CONTRACTS[0].id,from:'2026-08',until:''}).state;s=call(s,'criterion',{label:'Critério de teste',max:5}).state;return s;}
test('Avaliação exige vínculo, critérios e abertura; é única e classifica atraso',()=>{const s=configured();const data={schoolId:school.schoolId,contractId:CONTRACTS[0].id,month:'2026-08',answers:{[s.criteria[0].id]:4}};assert.throws(()=>call(s,'submitEvaluation',data,school,'2026-08-25T12:00:00Z','2026-08-25'));const a=call(s,'submitEvaluation',data,school);assert.equal(a.result.status,'Entregue no prazo');assert.throws(()=>call(a.state,'submitEvaluation',data,school));const late=call(s,'submitEvaluation',data,school,'2026-09-01T12:00:00Z','2026-09-01');assert.equal(late.result.timeliness,'Entregue em atraso');assert.equal(evaluationRows(s,'2026-07',manager).length,0);});
test('Correção mantém UUID, primeiro envio, critérios e histórico',()=>{let s=configured();const data={schoolId:school.schoolId,contractId:CONTRACTS[0].id,month:'2026-08',answers:{[s.criteria[0].id]:4}};const first=call(s,'submitEvaluation',data,school);s=call(first.state,'reviewEvaluation',{id:first.result.id,status:'Necessita correção',note:'Revisar resposta'}).state;const corrected=call(s,'submitEvaluation',data,school,'2026-09-02T12:00:00Z','2026-09-02');assert.equal(corrected.state.evaluations.length,1);assert.equal(corrected.result.id,first.result.id);assert.equal(corrected.result.history.length,3);assert.equal(corrected.result.timeliness,'Entregue no prazo');});
test('Filtros, recorrências e alertas derivam apenas dos registros',()=>{const a=call(initialState(),'createOccurrence',draft,school);assert.equal(filterOccurrences(a.state.occurrences,{contractId:CONTRACTS[1].id}).length,0);assert.ok(alertsFor(a.state.occurrences,a.state.settings,'2026-09-10T12:00:00Z').length>=2);assert.equal(patterns(a.state.occurrences,a.state.settings,'2026-08-29')[0].groups.length,0);assert.equal(evaluationStats([]).delivery,null);});
test('Exportação CSV neutraliza fórmulas e mantém aspas',()=>{assert.equal(csvCell('=1+1'),'"\'=1+1"');assert.equal(csvCell('a"b'),'"a""b"');});
