import { useState } from 'react';
import { useParams,useSearchParams } from 'react-router-dom';
import { useTransport } from './TransportContext';
import { useSeafin } from '../contexts/SeafinContext';
import { today,evaluationRows,evaluationWindow,evaluationStats,REVIEW_STATUSES,CONTRACTS } from './domain';
import { contractName,Bars } from './TransportUI';
import { Empty,Metric } from '../components/SeafinUI';
import { groups } from './domain';
export default function Evaluations(){
  const {schoolId:parameter}=useParams();const [query]=useSearchParams();const {state,actor,execute}=useTransport();const {schools}=useSeafin();const [month,setMonth]=useState(today().slice(0,7));const [contract,setContract]=useState(query.get('contrato')||'');const [selected,setSelected]=useState(null);const [answers,setAnswers]=useState({});const [notes,setNotes]=useState('');const [reviewStatus,setReviewStatus]=useState('Em revisão');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const schoolId=actor.role==='school'?actor.schoolId:parameter;const manager=actor.role==='seafin'&&!parameter;
  if(actor.role==='school'&&parameter&&parameter!==actor.schoolId)return <Empty>Acesso não autorizado.</Empty>;
  const window=evaluationWindow(month);const rows=evaluationRows(state,month,schoolId?{role:'school',schoolId}:actor).filter(r=>!contract||r.contractId===contract);const stats=evaluationStats(rows);
  const current=selected?rows.find(r=>r.id===selected):null;const criteria=current?.record?.criteria||state.criteria.filter(c=>c.active);
  function open(row){setSelected(row.id);setAnswers(row.record?.answers||{});setNotes('');setMessage('');}
  async function submit(e){e.preventDefault();setBusy(true);try{if(manager){await execute({type:'reviewEvaluation',data:{id:current.record.id,status:reviewStatus,note:notes}});}else{await execute({type:'submitEvaluation',data:{schoolId,contractId:current.contractId,month,answers,notes}},[],schoolId);}setSelected(null);setMessage(manager?'Revisão registrada.':'Avaliação enviada com sucesso.');}catch(err){setMessage(err.message);}finally{setBusy(false);}}
  return <><section className="panel"><h3>Avaliação Mensal do Transporte</h3><div className="toolbar"><label>Competência da avaliação<input type="month" required value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setSelected(null);}}}/></label><label>Contrato<select value={contract} onChange={e=>{setContract(e.target.value);setSelected(null);}}><option value="">Todos</option>{CONTRACTS.map(c=><option key={c.id} value={c.id}>{c.number}</option>)}</select></label></div><p>Recebimento abre em {window.opens}, cinco dias corridos antes do último dia do mês ({window.due}), no calendário de São Paulo. Envios após o mês são classificados em atraso.</p><p className="muted">A data de abertura não depende da presença de um registro. Critérios e vínculos devem estar configurados antes do envio.</p></section>
    <div className="metrics-grid"><Metric title="Avaliações esperadas" value={rows.length||'Sem vínculos'}/><Metric title="Recebidas" value={stats.received}/><Metric title="Entrega" value={stats.delivery==null?'Não calculável':`${stats.delivery.toFixed(1)}%`}/></div>
    {!rows.length?<Empty>Nenhum vínculo confirmado para esta competência. Não é possível presumir avaliações devidas pelas 82 escolas.</Empty>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Escola / CIE</th><th>Contrato</th><th>Competência</th><th>Situação</th><th>Envio</th><th>Ação</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{schools.find(s=>s.id===r.schoolId)?.name}<small>CIE {r.cie}</small></td><td>{contractName(r.contractId)}</td><td>{r.month}</td><td>{r.status}</td><td>{r.record?new Date(r.record.lastSubmittedAt).toLocaleString('pt-BR'):'Não enviada'}</td><td><button className="secondary" onClick={()=>open(r)}>{manager?'Consultar / revisar':'Abrir avaliação'}</button></td></tr>)}</tbody></table></div>}
    {current&&<section className="panel"><h3>{contractName(current.contractId)} · {month}</h3>{current.record&&<><p>Primeiro envio: {new Date(current.record.submittedAt).toLocaleString('pt-BR')} · {current.record.timeliness}</p><p>Observações da escola: {current.record.notes||'Nenhuma'}</p></>}
      <form onSubmit={submit}><fieldset disabled={busy}><div className="form-grid">{criteria.map(c=><label key={c.id}>{c.label} (0–{c.max})<input required type="number" min="0" max={c.max} step="0.1" disabled={manager||!!current.record&&current.record.status!=='Necessita correção'} value={answers[c.id]??''} onChange={e=>setAnswers({...answers,[c.id]:e.target.value===''?undefined:Number(e.target.value)})}/></label>)}</div>{!criteria.length&&<p className="error-box">Critérios ainda não configurados pelo SEAFIN.</p>}{manager&&current.record&&<label>Situação da revisão<select value={reviewStatus} onChange={e=>setReviewStatus(e.target.value)}>{REVIEW_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label>}<label>{manager?'Observação da revisão':'Observações da avaliação'}<textarea required={manager} value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="toolbar">{manager?current.record&&<button className="primary">Registrar revisão</button>:<button className="primary" disabled={today()<window.opens||!criteria.length||!!current.record&&current.record.status!=='Necessita correção'}>Enviar avaliação</button>}<button type="button" className="secondary" onClick={()=>setSelected(null)}>Fechar</button></div></fieldset></form>{current.record&&<ol className="timeline">{current.record.history.map(h=><li key={h.id}>{new Date(h.at).toLocaleString('pt-BR')} · {h.from||'Envio'} → {h.to} · {h.note}</li>)}</ol>}</section>}{message&&<p role="status" className="success-box">{message}</p>}<Bars title="Situação das avaliações" entries={groups(rows,'status')}/>
  </>;
}
