import { useState } from 'react';
import { useTransport } from './TransportContext';
import { useSeafin } from '../contexts/SeafinContext';
import { CONTRACTS,TYPES,SEVERITIES,today,applies } from './domain';
import { ACCEPT,prepareEvidence } from './repository';
export default function OccurrenceForm({schoolId,onDone}) {
  const {state,execute}=useTransport();const {schools}=useSeafin();const school=schools.find(s=>s.id===schoolId);
  const assignment=state.assignments.find(a=>a.schoolId===schoolId&&applies(a,today().slice(0,7)));
  const [draft,setDraft]=useState({schoolId,cie:assignment?.cie||school?.cie||'',contractId:assignment?.contractId||'',date:today(),time:'',studentReference:'',vehicle:'',driver:'',place:'',type:'',other:'',description:'',severity:''});
  const [files,setFiles]=useState([]);const [error,setError]=useState('');const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);
  const input=(key,label,type='text',required=true)=><label key={key}>{label}<input type={type} required={required} value={draft[key]} max={type==='date'?today():undefined} onChange={e=>{setConfirm(false);setDraft(d=>({...d,[key]:e.target.value}));}}/></label>;
  async function send(e){e.preventDefault();setError('');if(!files.length){setError('Inclua ao menos uma evidência.');return;}if(!confirm){setConfirm(true);return;}setBusy(true);try{const prepared=await prepareEvidence(files);const evidences=prepared.map(({blob: _blob,...metadata})=>metadata);const row=await execute({type:'createOccurrence',data:{...draft,evidences}},prepared,schoolId);onDone(row);}catch(err){setError(err.message);setConfirm(false);}finally{setBusy(false);}}
  return <section className="panel"><h3>Registrar nova ocorrência</h3><form onSubmit={send}><fieldset disabled={busy}><legend>1. Identificação e serviço</legend><p><strong>{school?.name}</strong></p><div className="form-grid"><label>Contrato<select required value={draft.contractId} onChange={e=>{setConfirm(false);setDraft(d=>({...d,contractId:e.target.value}));}}><option value="">Selecione o contrato</option>{CONTRACTS.map(c=><option key={c.id} value={c.id}>Contrato nº {c.number}</option>)}</select></label>{input('cie','CIE da escola')}{input('date','Data','date')}{input('time','Horário','time')}{input('vehicle','Veículo (identificação / placa)')}{input('driver','Motorista')}{input('place','Local da ocorrência')}{input('studentReference','Referência interna do estudante, quando aplicável','text',false)}</div><p className="muted">Use referência interna em vez de nome, diagnóstico ou documento do estudante. Este campo aparece somente no detalhamento, nunca nos relatórios gerais. O contrato indicado na ocorrência não cria um vínculo institucional automaticamente.</p></fieldset>
      <fieldset disabled={busy}><legend>2. O que aconteceu</legend><div className="form-grid"><label>Tipo de ocorrência<select required value={draft.type} onChange={e=>{setConfirm(false);setDraft(d=>({...d,type:e.target.value}));}}><option value="">Selecione</option>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label>{draft.type==='Outros'&&input('other','Especifique a ocorrência')}<label>Grau de gravidade<select required value={draft.severity} onChange={e=>{setConfirm(false);setDraft(d=>({...d,severity:e.target.value}));}}><option value="">Selecione</option>{Object.keys(SEVERITIES).map(s=><option key={s}>{s}</option>)}</select></label></div><div className="severity-help">{Object.entries(SEVERITIES).map(([key,text])=><p key={key}><strong>{key}:</strong> {text}</p>)}</div><label>Descrição detalhada<textarea required rows={4} value={draft.description} onChange={e=>{setConfirm(false);setDraft(d=>({...d,description:e.target.value}));}}/></label></fieldset>
      <fieldset disabled={busy}><legend>3. Evidências</legend><label>Fotos, vídeos ou documentos<input type="file" multiple accept={ACCEPT} onChange={e=>{setConfirm(false);setFiles(Array.from(e.target.files));}}/></label><p className="muted">Até 6 arquivos e 100 MB no total. JPEG, PNG, WebP e PDF: até 10 MB cada. MP4 e WebM: até 50 MB. Não inclua rostos ou dados de estudantes sem necessidade e autorização.</p><ul>{files.map((f,i)=><li key={i}>{f.name} · {(f.size/1024/1024).toFixed(2)} MB</li>)}</ul></fieldset>
      {error&&<p role="alert" className="error-box">{error}</p>}{confirm&&<div className="confirmation-box" role="status"><strong>Confirme antes de enviar</strong><p>{school?.name} · Contrato {CONTRACTS.find(c=>c.id===draft.contractId)?.number} · {draft.date} às {draft.time}</p><p>{draft.type} · Gravidade {draft.severity} · {files.length} evidências</p><p>Confira as informações. O protocolo será gerado após o salvamento.</p></div>}<div className="toolbar"><button className="primary" disabled={busy}>{busy?'Salvando…':confirm?'Confirmar e enviar ocorrência':'Revisar ocorrência'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>onDone(null)}>Cancelar</button></div></form></section>;
}

