import { useEffect,useState } from 'react';
import { useParams } from 'react-router-dom';
import { useTransport } from './TransportContext';
import { useSeafin } from '../contexts/SeafinContext';
import { readEvidence } from './repository';
import { contractName } from './TransportUI';
import { STATUSES,SEVERITIES,scoped } from './domain';
import { Empty } from '../components/SeafinUI';
function Evidence({file}) {
  const [url,setUrl]=useState('');const [error,setError]=useState('');
  useEffect(()=>{let active=true;let objectUrl;readEvidence(file.id).then(stored=>{if(!stored)throw Error('Arquivo não encontrado neste navegador.');objectUrl=URL.createObjectURL(stored.blob);if(active)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[file.id]);
  return <figure className="evidence-card">{url&&file.type.startsWith('image/')?<img src={url} alt={`Evidência: ${file.name}`}/>:url&&file.type.startsWith('video/')?<video src={url} controls preload="metadata"/>:null}<figcaption><strong>{file.name}</strong><p>{file.type} · {(file.size/1024/1024).toFixed(2)} MB</p><small>{new Date(file.uploadedAt).toLocaleString('pt-BR')}</small><details><summary>Integridade do arquivo</summary><small className="source-text">SHA-256: {file.sha256}</small></details>{url&&<a href={url} download={file.name}>Baixar evidência</a>}{error&&<p role="alert">{error}</p>}</figcaption></figure>;
}
export default function OccurrenceDetail(){
  const {id,schoolId}=useParams();const {state,actor,execute}=useTransport();const {schools}=useSeafin();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [draft,setDraft]=useState({status:'',responsible:'',note:'',action:'Observação',forwardedTo:'',companyResponse:'',reviewedSeverity:''});
  const row=scoped(state.occurrences,actor).find(r=>r.id===id&&(!schoolId||r.schoolId===schoolId));
  if(!row)return <Empty>Ocorrência não encontrada ou acesso não autorizado.</Empty>;
  const manager=actor.role==='seafin'&&!schoolId;
  async function treat(e){e.preventDefault();setBusy(true);try{await execute({type:'treatOccurrence',data:{...draft,id:row.id,status:draft.status||row.status,responsible:draft.responsible||row.responsible,expectedVersion:row.updatedAt}});setDraft({...draft,note:'',status:'',companyResponse:''});setError('Tratamento registrado com histórico.');}catch(err){setError(err.message);}finally{setBusy(false);}}
  const fields=[['Escola',schools.find(s=>s.id===row.schoolId)?.name],['CIE informado',row.cie],['Contrato',contractName(row.contractId)],['Data e horário',`${row.date} ${row.time}`],['Tipo',row.type==='Outros'?`${row.type}: ${row.other}`:row.type],['Veículo',row.vehicle],['Motorista',row.driver],['Local',row.place],['Gravidade informada pela escola',row.severity],['Classificação revisada pelo SEAFIN',row.reviewedSeverity||'Não revisada'],['Situação',row.status],['Responsável',row.responsible||'Não atribuído']];
  return <><section className="panel"><h3>{row.protocol}</h3><div className="detail-grid">{fields.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><h4>Descrição enviada</h4><p className="preserve-lines">{row.description}</p>{row.studentReference&&<details><summary>Referência restrita do estudante</summary><p>{row.studentReference}</p><small>Não incluída nos painéis ou exportações.</small></details>}</section><section className="panel"><h3>Galeria de evidências</h3><div className="evidence-grid">{row.evidences.map(f=><Evidence key={f.id} file={f}/>)}</div></section>
    {manager&&row.status!=='Encerrada'&&<section className="panel"><h3>Tratamento pelo SEAFIN</h3><form onSubmit={treat}><fieldset disabled={busy}><div className="form-grid"><label>Novo status<select value={draft.status||row.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{STATUSES.filter(s=>STATUSES.indexOf(s)>=STATUSES.indexOf(row.status)).map(s=><option key={s}>{s}</option>)}</select></label><label>Responsável<input required value={draft.responsible||row.responsible||''} onChange={e=>setDraft({...draft,responsible:e.target.value})}/></label><label>Tipo de providência<select value={draft.action} onChange={e=>setDraft({...draft,action:e.target.value})}>{['Observação','Providência','Encaminhamento','Retorno da empresa','Resolução','Encerramento'].map(s=><option key={s}>{s}</option>)}</select></label><label>Encaminhar para<input value={draft.forwardedTo} onChange={e=>setDraft({...draft,forwardedTo:e.target.value})}/></label><label>Revisão da gravidade (não altera o original)<select value={draft.reviewedSeverity} onChange={e=>setDraft({...draft,reviewedSeverity:e.target.value})}><option value="">Manter sem revisão</option>{Object.keys(SEVERITIES).map(s=><option key={s}>{s}</option>)}</select></label></div><label>Retorno da empresa<textarea value={draft.companyResponse} onChange={e=>setDraft({...draft,companyResponse:e.target.value})}/></label><label>Observação / providência obrigatória<textarea required rows={3} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><button className="primary">{busy?'Salvando…':'Registrar tratamento'}</button></fieldset></form>{error&&<p role="status">{error}</p>}</section>}
    <section className="panel"><h3>Histórico da ocorrência</h3><ol className="timeline">{row.history.map(h=><li key={h.id}><strong>{h.from||'Envio'} → {h.to}</strong><p>{new Date(h.at).toLocaleString('pt-BR')} · {h.actor}</p><p>{h.action} {h.note}</p>{h.forwardedTo&&<p>Encaminhada para: {h.forwardedTo}</p>}{h.companyResponse&&<p>Retorno da empresa: {h.companyResponse}</p>}</li>)}</ol></section></>;
}
