import { useState } from 'react';
import { useTransport } from './TransportContext';
import { useSeafin } from '../contexts/SeafinContext';
import { today,filterOccurrences,terminal,groups,evaluationRows,evaluationStats } from './domain';
import TransportFilters,{initialFilters} from './TransportFilters';
import { Bars,DownloadCSV,contractName } from './TransportUI';
import { Metric,Empty } from '../components/SeafinUI';
export default function TransportReports(){
  const {state,actor}=useTransport();const {schools}=useSeafin();const [filters,setFilters]=useState({...initialFilters,from:`${today().slice(0,7)}-01`,to:today()});const [generated,setGenerated]=useState(null);
  function generate(){if(!filters.from||!filters.to||filters.from>filters.to)return;const rows=filterOccurrences(state.occurrences,filters);const months=[];let month=filters.from.slice(0,7);while(month<=filters.to.slice(0,7)&&months.length<120){months.push(month);const [y,m]=month.split('-').map(Number);month=new Date(Date.UTC(y,m,1)).toISOString().slice(0,7);}const evaluations=months.flatMap(m=>evaluationRows(state,m,actor)).filter(r=>(!filters.schoolId||r.schoolId===filters.schoolId)&&(!filters.contractId||r.contractId===filters.contractId));setGenerated({rows,evaluations,filters:{...filters},at:new Date().toISOString(),truncated:month<=filters.to.slice(0,7)});}
  const rows=generated?.rows||[];const resolved=rows.filter(r=>r.resolvedAt);const average=resolved.length?resolved.reduce((sum,r)=>sum+(Date.parse(r.resolvedAt)-Date.parse(r.createdAt))/86400000,0)/resolved.length:null;const evalStats=evaluationStats(generated?.evaluations||[]);
  return <><TransportFilters value={filters} onChange={setFilters}/><button className="primary no-print" onClick={generate} disabled={!filters.from||!filters.to||filters.from>filters.to}>Gerar relatório</button>{!generated?<Empty>Selecione as datas inicial e final para gerar o relatório.</Empty>:<article className="transport-report"><header className="panel"><p>URE GUARULHOS SUL</p><h3>SEAFIN — Serviço de Administração e Finanças</h3><h4>TRANSPORTE ESCOLAR</h4><p>Relatório de Ocorrências e Acompanhamento</p><p>Período: {generated.filters.from} a {generated.filters.to} · Gerado em {new Date(generated.at).toLocaleString('pt-BR')}</p><p className="muted">Filtros: contrato {generated.filters.contractId?contractName(generated.filters.contractId):'todos'}; escola {schools.find(s=>s.id===generated.filters.schoolId)?.name||'todas'}; tipo {generated.filters.type||'todos'}; gravidade {generated.filters.severity||'todas'}; status {generated.filters.status||'todos'}; veículo {generated.filters.vehicle||'todos'}; motorista {generated.filters.driver||'todos'}; busca {generated.filters.search||'nenhuma'}.</p><p className="muted">Ocorrências filtradas pela data do fato. Avaliações abrangem as competências tocadas pelo período, somente com filtros de escola e contrato. O relatório é uma fotografia do momento da geração.</p>{generated.truncated&&<p role="alert">O relatório de avaliações foi limitado a 120 competências. Reduza o período.</p>}</header>
      <div className="toolbar no-print"><button className="secondary" onClick={()=>window.print()}>Imprimir / salvar como PDF</button><DownloadCSV name="transporte-ocorrencias.csv" headers={['Protocolo','Data','Escola','CIE','Contrato','Tipo','Veículo','Gravidade original','Status','Responsável','Criada em','Resolvida em']} rows={rows.map(r=>[r.protocol,r.date,schools.find(s=>s.id===r.schoolId)?.name,r.cie,contractName(r.contractId),r.type,r.vehicle,r.severity,r.status,r.responsible,r.createdAt,r.resolvedAt])}>Exportar ocorrências CSV</DownloadCSV><DownloadCSV name="transporte-avaliacoes.csv" headers={['Escola','CIE','Contrato','Competência','Situação','Primeiro envio','Pontualidade']} rows={generated.evaluations.map(r=>[schools.find(s=>s.id===r.schoolId)?.name,r.cie,contractName(r.contractId),r.month,r.status,r.record?.submittedAt,r.record?.timeliness])}>Exportar avaliações CSV</DownloadCSV></div>
      <div className="metrics-grid"><Metric title="Ocorrências" value={rows.length}/><Metric title="Resolvidas / encerradas" value={rows.filter(terminal).length}/><Metric title="Ainda em aberto" value={rows.filter(r=>!terminal(r)).length}/><Metric title="Tempo médio de resolução" value={average==null?'Sem dados':`${average.toFixed(1)} dias`} note="Do registro até a resolução"/></div><div className="module-grid"><Bars title="Por contrato" entries={groups(rows,'contractId')} label={contractName}/><Bars title="Por escola" entries={groups(rows,'schoolId')} label={id=>schools.find(s=>s.id===id)?.name||id}/><Bars title="Por tipo" entries={groups(rows,'type')}/><Bars title="Por gravidade original" entries={groups(rows,'severity')}/><Bars title="Por status" entries={groups(rows,'status')}/></div>
      <section className="panel"><h3>Avaliações mensais</h3><p>Quantidade esperada: {generated.evaluations.length||'não determinável sem vínculos'} · Recebidas: {evalStats.received} · Entrega: {evalStats.delivery==null?'não calculável':`${evalStats.delivery.toFixed(1)}%`}</p><p>No prazo: {evalStats.onTime} · Em atraso: {evalStats.late} · Em revisão: {evalStats.review} · Necessitam correção: {evalStats.correction} · Não entregues: {evalStats.missing}</p><p>Média normalizada: {evalStats.average==null?'não calculável (sem respostas ou critérios diferentes)':`${evalStats.average.toFixed(1)} / 100`}</p><p className="muted">A média usa somente avaliações com o mesmo conjunto de critérios e escalas; não é um ranking. Informações do estudante, descrições livres e arquivos de evidência não são exportados.</p></section>
    </article>}</>;
}
