import { useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { useTransport } from './TransportContext';
import { useSeafin } from '../contexts/SeafinContext';
import { Empty,Metric } from '../components/SeafinUI';
import { CONTRACTS,filterOccurrences,terminal,daysOpen,groups,patterns,alertsFor,evaluationRows,today } from './domain';
import { Bars,contractName } from './TransportUI';
import TransportFilters,{initialFilters} from './TransportFilters';
export function OccurrenceTable({rows}){const {schools}=useSeafin();return !rows.length?<Empty>Nenhuma ocorrência encontrada. Não há registros fictícios.</Empty>:<div className="table-scroll"><table className="data-table"><thead><tr>{['Protocolo / data','Escola','Contrato / tipo','Veículo','Gravidade','Status','Responsável','Tempo em aberto','Detalhes'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.protocol}<small>{r.date}</small></td><td>{schools.find(s=>s.id===r.schoolId)?.name}</td><td>{contractName(r.contractId)}<small>{r.type}</small></td><td>{r.vehicle}</td><td>{r.severity}</td><td>{r.status}</td><td>{r.responsible||'Não atribuído'}</td><td>{daysOpen(r)} dias{terminal(r)&&<small>Até a resolução</small>}</td><td><Link to={`/painel/transporte/ocorrencias/${r.id}`}>Abrir</Link></td></tr>)}</tbody></table></div>;}
export default function TransportDashboard(){
  const {contractId}=useParams();const {state,actor}=useTransport();const {schools,items}=useSeafin();const [f,setF]=useState({...initialFilters,contractId:contractId||''});
  const effective={...f,contractId:contractId||f.contractId};const rows=filterOccurrences(state.occurrences,effective);const alerts=alertsFor(rows,state.settings);const recurrence=patterns(rows,state.settings);
  const month=today().slice(0,7);const expected=evaluationRows(state,month,actor).filter(r=>(!effective.contractId||r.contractId===effective.contractId)&&(!f.schoolId||r.schoolId===f.schoolId));
  if(contractId&&!CONTRACTS.some(c=>c.id===contractId))return <Empty>Contrato não encontrado.</Empty>;
  return <>{contractId?<section className="panel"><h3>Contrato nº {contractName(contractId)}</h3><p>Empresa, vigência, valores, veículos cadastrados, motoristas cadastrados e documentos contratuais: não informados.</p><p>Escolas vinculadas: {state.assignments.filter(a=>a.contractId===contractId).map(a=>schools.find(s=>s.id===a.schoolId)?.name).join(', ')||'nenhuma confirmada'}</p><Link to={`/painel/transporte/avaliacoes?contrato=${contractId}`}>Avaliações deste contrato →</Link></section>:<div className="contract-links">{CONTRACTS.map(c=><Link key={c.id} to={`/painel/transporte/contratos/${c.id}`}>Contrato nº {c.number} →</Link>)}</div>}
    {items.some(i=>i.module==='transporte')&&<section className="panel"><h3>Registros operacionais anteriores</h3><p>Os registros do formulário genérico anterior foram preservados. Eles não têm todos os campos exigidos pelo novo fluxo e não foram convertidos em protocolos automaticamente.</p><Link to="/painel/ocorrencias">Consultar ocorrências anteriores →</Link></section>}
    <TransportFilters value={effective} onChange={setF} contractFixed={!!contractId}/><div className="metrics-grid">{[['Total de ocorrências',rows.length],['Ocorrências em aberto',rows.filter(r=>!terminal(r)).length],['Em análise',rows.filter(r=>r.status==='Em análise').length],['Em atendimento',rows.filter(r=>r.status==='Em atendimento').length],['Resolvidas / encerradas',rows.filter(terminal).length],['Gravidade alta original',rows.filter(r=>r.severity==='Alto').length],['Escolas com ocorrências',new Set(rows.map(r=>r.schoolId)).size],['Avaliações não enviadas',expected.length?expected.filter(r=>!r.record).length:'Sem vínculos']].map(([title,value])=><Metric key={title} title={title} value={value}/>)}</div><p className="muted">Avaliações: competência {month}, somente vínculos confirmados, por escola/contrato; não usa filtros de tipo, veículo, motorista ou status de ocorrência.</p>
    <section className="panel"><h3>Ocorrências de Transporte</h3><OccurrenceTable rows={rows}/></section><section className="panel"><h3>Alertas gerenciais</h3><p className="muted">Limites locais configuráveis: sem atendimento {state.settings.unattendedDays} dias; em aberto {state.settings.openDays} dias. Não indicam culpa ou responsabilidade.</p>{alerts.length?<ul>{alerts.map(a=><li key={a.id}><Link to={`/painel/transporte/ocorrencias/${a.occurrenceId}`}>{a.protocol}</Link> · {a.text}</li>)}</ul>:<p>Nenhum alerta derivado dos registros selecionados.</p>}</section>
    <div className="module-grid"><Bars title="Ocorrências ao longo do tempo" entries={groups(rows,'date')}/><Bars title="Ocorrências por tipo" entries={groups(rows,'type')}/><Bars title="Ocorrências por contrato" entries={groups(rows,'contractId')} label={contractName}/><Bars title="Ocorrências por escola" entries={groups(rows,'schoolId')} label={id=>schools.find(s=>s.id===id)?.name||id}/><Bars title="Gravidade informada pela escola" entries={groups(rows,'severity')}/><Bars title="Situação das ocorrências" entries={groups(rows,'status')}/><Bars title="Evolução mensal" entries={groups(rows.map(r=>({...r,month:r.date.slice(0,7)})),'month')}/><Bars title={`Avaliações — ${month}`} entries={groups(expected,'status')}/></div>
    <section className="panel"><h3>Padrões e Recorrências</h3><p>Contagens absolutas, sem ranking de desempenho ou atribuição de culpa. Mínimo de {state.settings.recurrenceCount} registros nos últimos {state.settings.recurrenceDays} dias, dentro dos filtros selecionados.</p>{recurrence.map(p=><div key={p.field}><h4>{{vehicle:'Veículos',driver:'Motoristas',schoolId:'Escolas',type:'Tipos de problema',contractId:'Contratos'}[p.field]}</h4>{p.groups.length?<ul>{p.groups.map(([key,n])=><li key={key}>{p.field==='contractId'?contractName(key):p.field==='schoolId'?schools.find(s=>s.id===key)?.name:key}: {n} registros</li>)}</ul>:<p className="muted">Nenhum padrão no limite configurado.</p>}</div>)}</section>
  </>;
}
