import { useState } from 'react';
import { useTransport } from './TransportContext';
import { useSeafin } from '../contexts/SeafinContext';
import { CONTRACTS,today } from './domain';
import { contractName } from './TransportUI';
export default function TransportSettings(){
  const {state,execute}=useTransport();const {schools}=useSeafin();const [assignment,setAssignment]=useState({schoolId:'',contractId:'',cie:'',from:today().slice(0,7),until:''});const [criterion,setCriterion]=useState({label:'',max:5});const [settings,setSettings]=useState(state.settings);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  async function submit(type,data){setBusy(true);try{await execute({type,data});setMessage('Configuração salva.');}catch(err){setMessage(err.message);}finally{setBusy(false);}}
  return <><section className="panel"><h3>Vínculos escola–contrato</h3><p>Cadastre somente vínculos confirmados. Eles definem as avaliações esperadas; não são inferidos a partir de ocorrências. Os números de contratos foram informados pelo usuário; outros dados contratuais permanecem ausentes.</p><form onSubmit={e=>{e.preventDefault();submit('assignment',assignment);}}><fieldset disabled={busy}><div className="form-grid"><label>Escola<select required value={assignment.schoolId} onChange={e=>setAssignment({...assignment,schoolId:e.target.value})}><option value="">Selecione</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Contrato<select required value={assignment.contractId} onChange={e=>setAssignment({...assignment,contractId:e.target.value})}><option value="">Selecione</option>{CONTRACTS.map(c=><option key={c.id} value={c.id}>{c.number}</option>)}</select></label><label>CIE confirmado<input required inputMode="numeric" pattern="[0-9]{1,10}" value={assignment.cie} onChange={e=>setAssignment({...assignment,cie:e.target.value})}/></label><label>Competência inicial<input required type="month" value={assignment.from} onChange={e=>setAssignment({...assignment,from:e.target.value})}/></label><label>Competência final (se conhecida)<input type="month" value={assignment.until} onChange={e=>setAssignment({...assignment,until:e.target.value})}/></label></div><button className="primary">Confirmar vínculo</button></fieldset></form><ul>{state.assignments.map(a=><li key={a.id}>{schools.find(s=>s.id===a.schoolId)?.name} · CIE {a.cie} · {contractName(a.contractId)} · {a.from} até {a.until||'não informado'}</li>)}</ul></section>
    <section className="panel"><h3>Critérios da avaliação mensal</h3><p>Nenhum critério institucional foi presumido. Configure os critérios aprovados. Cada avaliação guarda a versão e a escala utilizadas no envio; desativar um critério não altera avaliações antigas.</p><form onSubmit={e=>{e.preventDefault();submit('criterion',criterion);}}><fieldset disabled={busy}><div className="form-grid"><label>Critério<input required value={criterion.label} onChange={e=>setCriterion({...criterion,label:e.target.value})}/></label><label>Nota máxima (mínimo 0)<input type="number" min="1" max="100" step="1" required value={criterion.max} onChange={e=>setCriterion({...criterion,max:Number(e.target.value)})}/></label></div><button className="primary">Adicionar critério</button></fieldset></form><ul>{state.criteria.map(c=><li key={c.id}>{c.label} · escala 0–{c.max} · {c.active?'Ativo':'Inativo'} <button className="secondary" disabled={busy} onClick={()=>submit('toggleCriterion',{id:c.id})}>{c.active?'Desativar':'Ativar'}</button></li>)}</ul></section>
    <section className="panel"><h3>Limites de alertas</h3><p>Valores iniciais são parâmetros operacionais ajustáveis, não limites contratuais oficiais.</p><form onSubmit={e=>{e.preventDefault();submit('settings',settings);}}><fieldset disabled={busy}><div className="form-grid">{Object.entries({unattendedDays:'Dias sem atendimento',openDays:'Dias em aberto',recurrenceCount:'Quantidade mínima para recorrência',recurrenceDays:'Janela de recorrência (dias)'}).map(([key,label])=><label key={key}>{label}<input required type="number" min="1" max="365" step="1" value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}</div><button className="primary">Salvar limites</button></fieldset></form></section>{message&&<p role="status" className="success-box">{message}</p>}<details className="panel"><summary>Histórico de configuração</summary><ol className="timeline">{state.configurationHistory.map(h=><li key={h.id}>{new Date(h.at).toLocaleString('pt-BR')} · {h.actor} · {h.to} · {h.note}</li>)}</ol></details></>;
}
